//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.7 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2017.11.04 at 04:06:34 PM IST 
//


package localhost._8081.user;

import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.XmlElementDecl;
import javax.xml.bind.annotation.XmlRegistry;
import javax.xml.namespace.QName;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the localhost._8081.user package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {

    private final static QName _UpdateUserRequest_QNAME = new QName("http://localhost:8081/user", "updateUserRequest");
    private final static QName _UserAuthentication_QNAME = new QName("http://localhost:8081/user", "userAuthentication");
    private final static QName _GetUserInfoRequest_QNAME = new QName("http://localhost:8081/user", "getUserInfoRequest");
    private final static QName _UserType_QNAME = new QName("http://localhost:8081/user", "userType");
    private final static QName _GetUserInfoResponse_QNAME = new QName("http://localhost:8081/user", "getUserInfoResponse");
    private final static QName _User_QNAME = new QName("http://localhost:8081/user", "user");
    private final static QName _UpdateUserResponse_QNAME = new QName("http://localhost:8081/user", "updateUserResponse");
    private final static QName _UserUpdate_QNAME = new QName("http://localhost:8081/user", "userUpdate");

    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: localhost._8081.user
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link UserUpdate }
     * 
     */
    public UserUpdate createUserUpdate() {
        return new UserUpdate();
    }

    /**
     * Create an instance of {@link UserAuthentication }
     * 
     */
    public UserAuthentication createUserAuthentication() {
        return new UserAuthentication();
    }

    /**
     * Create an instance of {@link UpdateUserRequest }
     * 
     */
    public UpdateUserRequest createUpdateUserRequest() {
        return new UpdateUserRequest();
    }

    /**
     * Create an instance of {@link GetUserInfoResponse }
     * 
     */
    public GetUserInfoResponse createGetUserInfoResponse() {
        return new GetUserInfoResponse();
    }

    /**
     * Create an instance of {@link GetUserInfoRequest }
     * 
     */
    public GetUserInfoRequest createGetUserInfoRequest() {
        return new GetUserInfoRequest();
    }

    /**
     * Create an instance of {@link UserType }
     * 
     */
    public UserType createUserType() {
        return new UserType();
    }

    /**
     * Create an instance of {@link UpdateUserResponse }
     * 
     */
    public UpdateUserResponse createUpdateUserResponse() {
        return new UpdateUserResponse();
    }

    /**
     * Create an instance of {@link User }
     * 
     */
    public User createUser() {
        return new User();
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link UpdateUserRequest }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://localhost:8081/user", name = "updateUserRequest")
    public JAXBElement<UpdateUserRequest> createUpdateUserRequest(UpdateUserRequest value) {
        return new JAXBElement<UpdateUserRequest>(_UpdateUserRequest_QNAME, UpdateUserRequest.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link UserAuthentication }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://localhost:8081/user", name = "userAuthentication")
    public JAXBElement<UserAuthentication> createUserAuthentication(UserAuthentication value) {
        return new JAXBElement<UserAuthentication>(_UserAuthentication_QNAME, UserAuthentication.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link GetUserInfoRequest }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://localhost:8081/user", name = "getUserInfoRequest")
    public JAXBElement<GetUserInfoRequest> createGetUserInfoRequest(GetUserInfoRequest value) {
        return new JAXBElement<GetUserInfoRequest>(_GetUserInfoRequest_QNAME, GetUserInfoRequest.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link UserType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://localhost:8081/user", name = "userType")
    public JAXBElement<UserType> createUserType(UserType value) {
        return new JAXBElement<UserType>(_UserType_QNAME, UserType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link GetUserInfoResponse }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://localhost:8081/user", name = "getUserInfoResponse")
    public JAXBElement<GetUserInfoResponse> createGetUserInfoResponse(GetUserInfoResponse value) {
        return new JAXBElement<GetUserInfoResponse>(_GetUserInfoResponse_QNAME, GetUserInfoResponse.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link User }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://localhost:8081/user", name = "user")
    public JAXBElement<User> createUser(User value) {
        return new JAXBElement<User>(_User_QNAME, User.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link UpdateUserResponse }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://localhost:8081/user", name = "updateUserResponse")
    public JAXBElement<UpdateUserResponse> createUpdateUserResponse(UpdateUserResponse value) {
        return new JAXBElement<UpdateUserResponse>(_UpdateUserResponse_QNAME, UpdateUserResponse.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link UserUpdate }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://localhost:8081/user", name = "userUpdate")
    public JAXBElement<UserUpdate> createUserUpdate(UserUpdate value) {
        return new JAXBElement<UserUpdate>(_UserUpdate_QNAME, UserUpdate.class, null, value);
    }

}
