//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.7 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2017.11.04 at 04:06:34 PM IST 
//

@javax.xml.bind.annotation.XmlSchema(namespace = "http://localhost:8081/user", elementFormDefault = javax.xml.bind.annotation.XmlNsForm.QUALIFIED)
package localhost._8081.user;
